language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
env:
- PLONE_VERSION=4.2 TEST_EGGS=buildout:test-eggs=Pillow
- PLONE_VERSION=4.3
matrix:
  include:
  - python: 2.6
    env: PLONE_VERSION=4.1 TEST_EGGS=buildout:test-eggs=Pillow
  fast_finish: true
install:
- sed -ie "s#test-4.3.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
- python bootstrap.py --buildout-version=2.5.3 --setuptools-version=20.1.1
- bin/buildout $TEST_EGGS annotate
- bin/buildout $TEST_EGGS
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
