language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
- PLONE_VERSION=4.2 TEST_EGGS=buildout:test-eggs=Pillow
- PLONE_VERSION=4.3
matrix:
  include:
  - python: 2.6
    env: PLONE_VERSION=4.1 TEST_EGGS=buildout:test-eggs=Pillow
  fast_finish: true
install:
- sed -ie "s#test-4.3.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
- python bootstrap.py
- bin/buildout $TEST_EGGS annotate
- bin/buildout $TEST_EGGS
script:
- bin/test
notifications:
  irc: irc.freenode.org#plone-testing
